#To launch the interactive bokehpivot interface, you'll need the "reeds" conda environment
#For more details on the issue with "reeds2", see https://github.nrel.gov/ReEDS/ReEDS-2.0/issues/1146.
name: reeds
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - bokeh=2.4.2
  - gitpython=3.1.18
  - h5py=3.6.0
  - matplotlib=3.5.0
  - numpy=1.20.3
  - openpyxl=3.0.9
  - pandas=1.3.5
  - pip=21.2.4
  - pytables=3.6.1
  - requests=2.26.0
  - scikit-learn=1.0.1
  - click=8.1.3
  - julia>=1.7
  - scipy
  - ipykernel
  - git-lfs
  - tqdm
  - networkx
  - pytest
  - pip:
    - geopandas==0.10.2
    - cmocean==2.0
    - gdxpds==1.2.0
    - shapely==1.8.0
    - proj==0.2.0
    - pyproj==3.3.0
    - pulp==2.6.0
