static_presets = [
    {'name': 'Error Check', 'result': 'Error Check', 'preset': 'Errors'},
    {'name': 'Generation (TWh)', 'result': 'Generation National (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Capacity (GW)', 'result': 'Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Annual Capacity (GW)', 'result': 'New Annual Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Annual Retirements (GW)', 'result': 'Annual Retirements National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Regional Gen Final (TWh)', 'result': 'Generation BA (TWh) [no-index]', 'preset': 'Regional Gen Final'},
    {'name': 'Firm Capacity (GW)', 'result': 'Firm Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Final Gen by timeslice (GW)', 'result': 'Gen by timeslice national (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Curtailment Rate', 'result': 'Average VRE Curtailment', 'preset': 'Curt Rate Over Time'},
    {'name': 'Curtailment by BA (TWh)', 'result': 'Curtailment by BA (TWh)', 'preset': 'PCA Map Final'},
    {'name': 'Losses (fraction of load)', 'result': 'Losses (TWh)', 'preset': 'Fractional Losses by Type Over Time'},
    {'name': 'Transmission (GW-mi)', 'result': 'Transmission (GW-mi)', 'preset': 'Transmission Capacity'},
    {'name': 'Transmission Capacity Network', 'result': 'Transmission Capacity Network (GW)', 'preset': 'Map Final'},
    {'name': 'Bulk System Electricity Price ($/MWh)', 'result': 'Requirement Prices and Quantities National', 'preset': 'Bulk System Electricity Price ($/MWh)'},
    {'name': 'National Energy Price ($/MWh)', 'result': 'Requirement Prices and Quantities National', 'preset': 'Energy Price Lines ($/MWh)'},
    {'name': 'National Energy Price by timeslice ($/MWh)', 'result': 'Requirement Prices and Quantities National', 'preset': 'Energy Price by Timeslice Final ($/MWh)'},
    {'name': 'Final Regional Energy Price ($/MWh)', 'result': 'Requirement Prices and Quantities BA', 'preset': 'Energy Price Final BA Map ($/MWh)'},
    {'name': 'National Seasonal Capacity Price ($/kW-yr)', 'result': 'Requirement Prices and Quantities National', 'preset': 'ResMarg Season Price Lines ($/kW-yr)'},
    {'name': 'National Annual Capacity Price ($/kW-yr)', 'result': 'Requirement Prices and Quantities National', 'preset': 'ResMarg Price Lines ($/kW-yr)'},
    {'name': 'National RE Energy Price ($/MWh)', 'result': 'RE Generation Price ($/MWh)', 'preset': 'Scenario Lines Over Time'},
    {'name': 'RE Capacity Price by BA ($/kW-yr)', 'result': 'RE Capacity Price BA ($/kW-yr)', 'preset': 'RE Cap Price by BA'},
    {'name': 'Present Value of System Cost through 2050 (Bil $)', 'result': 'Sys Cost Annualized (Bil $)', 'preset': 'Discounted through 2050'},
    {'name': 'CO2 Emissions National (MMton)', 'result': 'CO2 Emissions National (MMton)', 'preset': 'Scenario Lines Over Time'},
    {'name': 'Wind Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['wind-ons','wind-ofs']}}},
    {'name': 'PV Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['upv','distpv']}}},
    {'name': 'CSP Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['csp']}}},
    {'name': 'Biopower Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['biopower','lfill-gas']}}},
    {'name': 'Battery Storage Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['battery', 'battery_2', 'battery_4', 'battery_6', 'battery_8', 'battery_10', 'battery_12', 'battery_24', 'battery_48', 'battery_72', 'battery_100', 'battery_li']}}},
    {'name': 'RE Turbine Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['h2-ct','h2-cc']}}},
    {'name': 'Upgraded Capacity (GW)', 'result': 'Upgraded Capacity (GW)', 'preset': 'Stacked Bars'},
]
