static_presets = [
    {'name': 'Error Check', 'result': 'Error Check', 'preset': 'Errors'},
    {'name': 'Intertemporal Capacity by Iteration (GW)', 'result': 'Capacity Iteration (GW)', 'preset': 'Explode By Tech'},
    {'name': 'Generation (TWh)', 'result': 'Generation National (TWh)', 'preset': 'Stacked Bars'},
    {'name': 'Capacity (GW)', 'result': 'Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'New Annual Capacity (GW)', 'result': 'New Annual Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Annual Retirements (GW)', 'result': 'Annual Retirements National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Final Gen by timeslice (GW)', 'result': 'Gen by timeslice national (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Regional Gen Final (TWh)', 'result': 'Generation BA (TWh) [no-index]', 'preset': 'Regional Gen Final'},
    {'name': 'Operating Reserves (TW-h)', 'result': 'Operating Reserves (TW-h)', 'preset': 'Stacked Bars'},
    {'name': 'Final OpRes by timeslice (GW)', 'result': 'Operating Reserves by Timeslice National (GW)', 'preset': 'Stacked Bars Final'},
    {'name': 'Firm Capacity (GW)', 'result': 'Firm Capacity National (GW)', 'preset': 'Stacked Bars'},
    {'name': 'Curtailment Rate', 'result': 'Average VRE Curtailment', 'preset': 'Curt Rate Over Time'},
    {'name': 'Losses (fraction of load)', 'result': 'Losses (TWh)', 'preset': 'Fractional Losses by Type Over Time'},
    {'name': 'Transmission (GW-mi)', 'result': 'Transmission (GW-mi)', 'preset': 'Transmission Capacity stacked bars'},
    {'name': 'Transmission (PRM) (GW-mi)', 'result': 'Transmission (GW-mi)', 'preset': 'Transmission Capacity (PRM) stacked bars'},
    {'name': 'Bulk System Electricity Price ($/MWh)', 'result': 'Requirement Prices and Quantities National', 'preset': 'Bulk System Electricity Price ($/MWh)'},
    {'name': 'National Energy Price ($/MWh)', 'result': 'Requirement Prices and Quantities National', 'preset': 'Energy Price Lines ($/MWh)'},
    {'name': 'Final National Energy Price by timeslice ($/MWh)', 'result': 'Requirement Prices and Quantities National', 'preset': 'Energy Price by Timeslice Final ($/MWh)'},
    {'name': 'National Average Electricity Cost ($/MWh)', 'result': 'National Average Electricity Cost ($/MWh)', 'preset': 'Average Electricity Cost by Year ($/MWh)'},
    {'name': 'National OpRes Price ($/MW-h)', 'result': 'Requirement Prices and Quantities National', 'preset': 'OpRes Price Lines ($/MW-h)'},
    {'name': 'Final National OpRes Price by timeslice ($/MW-h)', 'result': 'Requirement Prices and Quantities National', 'preset': 'OpRes Price by Timeslice Final ($/MW-h)'},
    {'name': 'Final Regional Energy Price ($/MWh)', 'result': 'Requirement Prices and Quantities BA', 'preset': 'Energy Price Final BA Map ($/MWh)'},
    {'name': 'National Annual Capacity Price ($/kW-yr)', 'result': 'Requirement Prices and Quantities National', 'preset': 'ResMarg Price Lines ($/kW-yr)'},
    {'name': 'Present Value of System Cost through 2050 (Bil $)', 'result': 'Sys Cost Annualized (Bil $)', 'preset': 'Discounted through 2050'},
    {'name': 'Emissions National (metric tons)', 'result': 'Emissions National (metric tons)', 'preset': 'Scenario Lines Over Time'},
    {'name': 'Net CO2e Emissions National (MMton)', 'result': 'Net CO2e Emissions National (MMton)', 'preset': 'Stacked Bars Over Time'},
    {'name': 'CO2 Abatement Cost ($/metric ton)', 'result': 'CO2 Price ($/metric ton)', 'preset': 'CO2 price over time'},
    {'name': 'Undiscounted Annualized System Cost (Bil $)', 'result': 'Sys Cost Annualized (Bil $)', 'preset': 'Undiscounted by Year'},
    {'name': 'Hydrogen Production (Million metric tons)', 'result': 'Production (Million metric tons)', 'preset': 'H2 Stacked Bars'},
    {'name': 'Hydrogen Price ($ per kg)', 'result': 'Hydrogen Price ($/kg)', 'preset': 'Lines'},
    {'name': 'Final Wind Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['wind-ons','wind-ofs']}}},
    {'name': 'Final PV Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['upv','dupv','distpv']}}},
    {'name': 'Area used for UPV (sq. km.)', 'result': 'UPV land area (sq. km.)', 'preset': 'Total UPV land area'},
    {'name': 'Final CSP Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['csp']}}},
    {'name': 'Final Biopower Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['biopower','lfill-gas']}}},
    {'name': 'Final Geothermal Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['geothermal']}}},
    {'name': 'Final Hydro and Canadian Import Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['hydro','Canada']}}},
    {'name': 'Final Pumped-hydro Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['pumped-hydro','pumped-hydro-flex']}}},
    {'name': 'Final Battery Storage Capacity (GW)', 'result': 'Capacity BA (GW)', 'preset': 'PCA Map Final by Tech','config':{'explode_group':'None','filter':{'tech':['battery', 'battery_2', 'battery_4', 'battery_6', 'battery_8', 'battery_10', 'battery_12', 'battery_24', 'battery_48', 'battery_72', 'battery_100']}}},
    {'name': 'Capacity Factor - Generation', 'result': 'Capacity Factor ivrt', 'preset': 'CF weighted ave'},
    {'name': 'Retail rate (¢/kWh)', 'result': 'Retail rate (¢/kWh)', 'preset': 'Lines'},
    {'name': 'New Tech Value Factors', 'result': 'Value New Techs', 'preset': 'VF by Year Explode Scenario'},
    {'name': 'Monetized health damages over time (billion $/year)', 'result': 'Health Damages from Emissions', 'preset': 'Monetized health damages over time'},
    {'name': 'Mortality over time (lives/year)', 'result': 'Health Damages from Emissions', 'preset': 'Mortality over time'},
    {'name': 'Total undiscounted health damages through 2050 (billion $)', 'result': 'Health Damages from Emissions', 'preset': 'Total undiscounted health damages through 2050'},
    {'name': 'Total discounted health damages through 2050 (billion $)', 'result': 'Health Damages from Emissions', 'preset': 'Total discounted health damages through 2050'},
    {'name': 'Total mortality through 2050 (lives)', 'result': 'Health Damages from Emissions', 'preset': 'Total mortality through 2050'},
    {'name': 'System cost + health damages: ACS ($/MWh)', 'result': 'Total Social Costs', 'preset': 'System cost + health damages: ACS CR'},
    {'name': 'System cost + health damages: H6C ($/MWh)', 'result': 'Total Social Costs', 'preset': 'System cost + health damages: H6C CR'},
    {'name': 'NEUE (ppm)', 'result': 'Resource adequacy', 'preset': 'Normalized expected unserved energy [%]'},
    {'name': 'Runtime (hours)', 'result': 'Runtime', 'preset': 'Stacked Bars'},
    {'name': 'Runtime by year (hours)', 'result': 'Runtime', 'preset': 'Stacked Bars by Year'},
]
