# this workflow sets up dependencies, builds the documentation, and updates the gh-pages branch
# the gh-pages branch is what's used for GitHub Pages

name: Documentation

on: 
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
      
      - name: Set environment variable for internal or external build
        run: echo 'BASE_URL="github.com/NREL/ReEDS-2.0"' >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==7.2.6
          pip install myst-parser==2.0.0
          pip install sphinx_rtd_theme==2.0.0

      - name: Build Sphinx documentation
        run: sphinx-build docs/source docs/build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build